
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { useRef, useState } from 'react'
import { AllCarDto, CarDtoWithoutFavorite } from '../../@types/dto'
import db from '../../prisma'
import { FooterMain } from '../../src/component/actual/FooterMain'
import BarMenu from '../../src/component/BarMenu'
import { MenuBar } from '../../src/component/Menu'
import { Modal } from '../../src/component/Modal'
import { ModalFavorite } from '../../src/component/ModalFavorite'
import { TradeinModal } from '../../src/component/ModalTwo'
import { getDataFromRedis, redisClient } from '../../src/services/redis'
import { NewGeelyComponent } from '../../src/component/actual/brendsPages/geely/NewCarComponent'
import { GeelyImgDestop } from '../../src/component/actual/brendsPages/geely/banner/GeelyImg'
import MapBrand from '../../src/component/actual/brendsPages/geely/MapBrand'
import { Box } from '@mui/material'
import News from '../../src/component/actual/brendsPages/geely/news/News'

type Brand = {
  brandName: string;
  count: string
}

const GeelyPage: NextPage<{ cars: AllCarDto, brands: Brand[] }> = ({ cars, brands }) => {

  console.log(brands)
  const [showModal, setShowModal] = useState(false)
  const [showTradeInModal, setShowTradeInModal] = useState(false)
  const [showModalFavorite, setShowModalFavorite] = useState(false)
  const refSales = useRef<HTMLDivElement>(null)
  const refTop = useRef<HTMLDivElement>(null)
  const refContact = useRef<HTMLDivElement>(null)
  const refAdvatages = useRef<HTMLDivElement>(null)
  const refFooter = useRef<HTMLDivElement>(null)
  const refForm = useRef<HTMLDivElement>(null)

  return (
    <>
      <Head>
        <title>АРКОНТ ОФИЦИАЛЬНЫЙ ДИЛЕР GEELY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuBar />
      <BarMenu />
      {/* < BannerGeely /> */}
      <div className='background'>
        <div className='content'>
          <GeelyImgDestop />
          <MapBrand />
          <NewGeelyComponent setShowModal={setShowModal} setShowModalFavorite={setShowModalFavorite} cars={cars} brands={brands} />
          <News />
        </div>
      </div >
      <FooterMain setShowTradeInModal={setShowTradeInModal} refs={{ refFooter }} />

      {
        showModal && <Modal showModal={showModal} setShowModal={setShowModal} />
      }

      {
        showTradeInModal && <TradeinModal showTradeInModal={showTradeInModal} setShowTradeInModal={setShowTradeInModal} />
      }

      {
        showModalFavorite && <ModalFavorite showModalFavorite={showModalFavorite} setShowModalFavorite={setShowModalFavorite} cars={cars} />
      }

      <style jsx>
        {` 
          .background {
            display: flex; 
            justify-content: center;
            width: '100%' ;
          }
  
          .content {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 1179px; 
          }

          @media(max-width: 1300px) {
            .content {  
              width: 970px; 
            }
          }

          @media(max-width: 900px) {
            .content{  
              width: 640px; 
            }
          }
        `}
      </style>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  try {
    const cars = await db.car.findMany({
      where: {
        active: true,
        CarModel: {
          brandName: 'Geely',
        }
      },
      include: {
        CarModel: true,
        CarComplectation: true,
        CarModification: true,
        extras: true,
        DealerModel: true,
      },
    });

    const brandsWithCount = await db.carModel.groupBy({
      by: ['brandName'],
      _count: true,
    });

    const brands = brandsWithCount.map((item) => ({
      brandName: item.brandName,
      count: item._count,
    }));


    const geelyCarCount = await db.car.count({
      where: {
        CarModel: {
          brandName: "Geely"
        }
      },
    });

    // const brands = await db.carModel.findMany({
    //   distinct: ['brandName'],
    //   select: {
    //     brandName: true,
    //   },
    // }).then((result) => result.map((item) => item.brandName).filter(Boolean));

    // Устанавливаем заголовки Cache-Control и ETag
    context.res.setHeader('Cache-Control', 'public, max-age=14400'); // Максимальное время кэширования - 4 часа
    context.res.setHeader('ETag', 'some-unique-value'); // Уникальное значение ETag

    return {
      props: {
        cars: JSON.parse(JSON.stringify(cars)),
        brands: JSON.parse(JSON.stringify(brands)),
      },
    };
  } catch (error) {
    console.error('Error querying the database:', error);
    return {
      props: {
        cars: [],
        brands: []
      },
    };
  }
}




// export const getServerSideProps: GetServerSideProps = async (context) => {
//   let cars: CarDtoWithoutFavorite[] = []; // Объявление переменной cars
//   let brands: string[] = []; // Объявление переменной brandsF
//   try {
//     // Получаем данные из Redis и парсим их в массив объектов
//     const carsData: string = await getDataFromRedis('cars-Geely');
//     const brandsData: string = await getDataFromRedis('brands');

//     if (!carsData) {
//       cars = await db.car.findMany(
//         {
//           where: {
//             active: true,
//             CarModel: {
//               brandName: 'Geely',
//             },
//           },
//           include: {
//             CarModel: true,
//             CarComplectation: true,
//             CarModification: true,
//             extras: true,
//             DealerModel: true,
//           },
//         }
//       );
//       // Сохраняем данные в Redis на день
//       redisClient.set('cars-Geely', JSON.stringify(cars), 'EX', 21600);
//     } else {
//       cars = JSON.parse(carsData) as CarDtoWithoutFavorite[]; // Преобразование строки в массив объектов типа Car
//     }

//     if (!brandsData) {
//       // Получаем все доступные бренды без повторений только с полем brandName
//       brands = await db.carModel.findMany({
//         distinct: ['brandName'],
//         select: {
//           brandName: true,
//         },
//       }).then((result) => result.map((item) => item.brandName).filter(Boolean));
//       // Сохраняем данные в Redis на день
//       redisClient.set('brands', JSON.stringify(brands), 'EX', 21600);
//     } else {
//       brands = JSON.parse(brandsData) as string[]; // Преобразование строки в массив объектов типа Car
//     }

//     // Устанавливаем заголовки Cache-Control и ETag
//     context.res.setHeader('Cache-Control', 'public, max-age=21600'); // Максимальное время кэширования - 4 часа
//     context.res.setHeader('ETag', 'some-unique-value'); // Уникальное значение ETag
//     context.res.setHeader('X-XSS-Protection', '1; mode=block');
//     context.res.setHeader('X-Frame-Options', 'SAMEORIGIN');
//     context.res.setHeader('X-Content-Type-Options', 'nosniff');
//     return {
//       props: {
//         cars,
//         brands
//       },
//     };

//   } catch (error) {
//     console.error('Error querying the database:', error);
//     return {
//       props: {
//         cars: [],
//         brands:[]
//       },
//     };
//   }
// }

export default GeelyPage




