version: '3.4'

services:
  app:
    image: testapp
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      NODE_ENV: production
    networks:
      - arkont-net
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - "db"
    # command: sh -c "./wait-for-it.sh db:5432 && npx prisma migrate deploy && npm start"
    command: "sleep 3 && npx prisma migrate deploy && npm start"


  # Добавляем контейнер Redis
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    environment:
      NODE_ENV: production
      REDIS_HOST: https://test.opel-arkont-volgograd.ru #указываем тут хост 
      REDIS_PORT: 6379 
    ports:
      - 6379:6379
    command: redis-server
    networks:
      - arkont-net

  db:
    env_file:
      - .env
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: user12345
      POSTGRES_DB: development_db
    ports:
       - "5432:5432"
    volumes:
       - "db-data:/var/lib/postgresql/data:rw"
    networks:
      - arkont-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - PMA_ARBITRARY=1
    networks:
      - arkont-net
  
volumes:
    db-data: {}
    
networks:
  arkont-net:
    name: arkont-net
