import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useRef, useState } from 'react'
import CompareCars from '../../src/component/actual/compareCarPage/CompareCards'
import { FooterMain } from '../../src/component/actual/FooterMain'
import BarMenu from '../../src/component/BarMenu'
import { MenuBar } from '../../src/component/Menu'
import { Modal } from '../../src/component/Modal'
import { TradeinModal } from '../../src/component/ModalTwo'
import { useRouter } from 'next/router'
import { MenuBarNew } from '../../src/component/actual/menuNew/Menu'
import { FooterMainNew } from '../../src/component/actual/menuNew/FooterMain'
import CompareCarsNew from '../../src/component/actual/compareCarPage/CompareCardsNew'
import { BannerCompare } from '../../src/component/actual/compareCarPage/BannerCompare'


const FavoriteCarPage: NextPage = () => {

    const [showModal, setShowModal] = useState(false)
    const [showTradeInModal, setShowTradeInModal] = useState(false)
    const [compareArr, setCompareArr] = useState([]);
    const [compareArrUsed, setCompareArrUsed] = useState([]);


    const router = useRouter()

    const refFooter = useRef<HTMLDivElement>(null)
    const refCards = useRef<HTMLDivElement>(null)

    //новые  для сравнения 
    useEffect(() => {
        async function start() {
            const res = await fetch('/api/favorite/compare/getAll', {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json'
                }
            })
            if (res.ok) {
                const result = await res.json()
                setCompareArr(result.compareCarUser.compareCars)
            } else {
                setCompareArrUsed(null)
            }
        }
        start()
    }, [])


    //с пробегом для сравнения 
    useEffect(() => {
        async function startCompare() {
            const res = await fetch('/api/usedcompare/getAll', {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json'
                }
            })
            if (res.ok) {
                // console.log(res)
                const result = await res.json()
                result !== undefined ?
                    setCompareArrUsed(result.compareCarUser.compareUsedCars)
                    :
                    setCompareArrUsed(null)


            }
        }
        startCompare()
    }, [])

    // useEffect(() => {
    //     console.log( compareArr)
    //     console.log(compareArrUsed)
    // }, [ compareArr, compareArrUsed])



    return (
        <>
            <Head>
                <title>АРКОНТ ОФИЦИАЛЬНЫЙ ДИЛЕР В ВОЛГОГРАДЕ</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MenuBarNew setShowModal={setShowModal} />
            <BarMenu />
            <div className='background'>
                <div className='content'>
                    <BannerCompare refs={{ refCards }} />
                    {/* <CompareCars
                compareArr={compareArr} setCompareArr={setCompareArr}
                compareArrUsed={compareArrUsed} setCompareArrUsed={setCompareArrUsed}
                setShowModal={setShowModal}
            /> */}
                    <CompareCarsNew
                        refCards={refCards}
                        compareArr={compareArr}
                        setCompareArr={setCompareArr}
                        compareArrUsed={compareArrUsed}
                        setCompareArrUsed={setCompareArrUsed}
                        setShowModal={setShowModal}
                    />
                </div>
            </div >
            <FooterMainNew setShowModal={setShowModal} refs={{ refFooter }} />

            {
                showModal && <Modal showModal={showModal} setShowModal={setShowModal} />
            }

            {
                showTradeInModal && <TradeinModal showTradeInModal={showTradeInModal} setShowTradeInModal={setShowTradeInModal} />
            }
            <style jsx>
                {` 
          .background {
            display: flex; 
            justify-content: center;
            width: '100%' ;
          }
  
          .content {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 1179px; 
          }

          .title {
            display: flex;
            justify-content: start;
            width: 100%;
            font-family: 'Roboto',sans-serif;
            margin-top: 20px;
            font-size: 25px;
            font-weight: bold;
          }

          @media(max-width: 1300px) {
            .content {  
              width: 970px; 
            }
          }

          @media(max-width: 900px) {
            .content{  
              width: 640px; 
            }
          }

          @media(max-width: 640px) {
            .content{  
              width: 450px; 
            }
            .title {
              justify-content: center;
            }
          }    
          
          @media(max-width: 450px) {
            .content{  
              width: 360px; 
            }
          }

          @media(max-width: 360px) {
            .background {
              padding-left: 10px;
              padding-right: 10px;
            }
            .content{  
              width:90%; 
            }
          }

        `}
            </style>
        </>
    )
}

export default FavoriteCarPage





