import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useRef, useState } from 'react'
import CompareCars from '../../src/component/actual/compareCarPage/CompareCards'
import { FooterMain } from '../../src/component/actual/FooterMain'
import BarMenu from '../../src/component/BarMenu'
import { MenuBar } from '../../src/component/Menu'
import { Modal } from '../../src/component/Modal'
import { TradeinModal } from '../../src/component/ModalTwo'
import { useRouter } from 'next/router'


const FavoriteCarPage: NextPage = () => {

    const [showModal, setShowModal] = useState(false)
    const [showTradeInModal, setShowTradeInModal] = useState(false)
    const [compareArr, setCompareArr] = useState([]);
    const [compareArrUsed, setCompareArrUsed] = useState([]);

    const router = useRouter()


    const refSales = useRef<HTMLDivElement>(null)
    const refTop = useRef<HTMLDivElement>(null)
    const refContact = useRef<HTMLDivElement>(null)
    const refAdvatages = useRef<HTMLDivElement>(null)
    const refFooter = useRef<HTMLDivElement>(null)
    const refForm = useRef<HTMLDivElement>(null)

    //новые  для сравнения 
    useEffect(() => {
        async function start() {
            const res = await fetch('/api/favorite/compare/getAll', {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json'
                }
            })
            if (res.ok) {
                const result = await res.json()
                setCompareArr(result.compareCarUser.compareCars)
               
            }
        }
        start()
    }, [])



    useEffect(() => {
        async function startCompare() {
            const res = await fetch('/api/usedcompare/getAll', {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json'
                }
            })
            if (res.ok) {
                // console.log(res)
                const result = await res.json()
                result !== undefined ?
                    setCompareArrUsed(result.compareCarUser.compareUsedCars)
                    :
                    setCompareArrUsed(null)

              
            }
        }
        startCompare()
    }, [])



    return (
        <>
            <Head>
                <title>АРКОНТ ОФИЦИАЛЬНЫЙ ДИЛЕР В ВОЛГОГРАДЕ</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MenuBar />
            <BarMenu />
            <CompareCars
                compareArr={compareArr} setCompareArr={setCompareArr}
                compareArrUsed={compareArrUsed} setCompareArrUsed={setCompareArrUsed}
                setShowModal={setShowModal}
            />
            <FooterMain setShowTradeInModal={setShowTradeInModal} refs={{ refFooter }} />

            {
                showModal && <Modal showModal={showModal} setShowModal={setShowModal} />
            }

            {
                showTradeInModal && <TradeinModal showTradeInModal={showTradeInModal} setShowTradeInModal={setShowTradeInModal} />
            }

        </>
    )
}

export default FavoriteCarPage





