import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useRef, useState } from 'react'
import FavoriteCars from '../../src/component/actual/favoriteCarPage/FavoriteCards'
import FavoriteCardsUsed from '../../src/component/actual/favoriteCarPage/FavoriteCardsUsed'
import { FooterMain } from '../../src/component/actual/FooterMain'
import BarMenu from '../../src/component/BarMenu'
import { MenuBar } from '../../src/component/Menu'
import { Modal } from '../../src/component/Modal'
import { TradeinModal } from '../../src/component/ModalTwo'
import { MenuBarNew } from '../../src/component/actual/menuNew/Menu'
import { FooterMainNew } from '../../src/component/actual/menuNew/FooterMain'
import { BannerFavorite } from '../../src/component/actual/favoriteCarPage/BannerFavorite'
import FavoriteCarsNew from '../../src/component/actual/favoriteCarPage/cards/FavoriteCardsNew'


const FavoriteCarPage: NextPage = () => {



    const [showModal, setShowModal] = useState(false)
    const [showTradeInModal, setShowTradeInModal] = useState(false)
    const [favArr, setFavArr] = useState([]);
    const [favArrUsed, setFavArrUsed] = useState([]);
    const refCards = useRef<HTMLDivElement>(null)
    const refFooter = useRef<HTMLDivElement>(null)



    useEffect(() => {
        async function start() {
            const res = await fetch('/api/favorite/getAll', {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json'
                }
            })
            if (res.ok) {
                const result = await res.json()
                setFavArr(result.favoriteCarUser.favoriteCars)
            }
        }
        start()
    }, [])


    useEffect(() => {
        async function start() {
            const res = await fetch('/api/usedfavorite/getAll', {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json'
                }
            })
            if (res.ok) {
                const result = await res.json()
                setFavArrUsed(result.favoriteCarUser.favoriteUsedCars)
            }
        }
        start()
    }, [])

    



    return (
        <>
            <Head>
                <title>АРКОНТ ОФИЦИАЛЬНЫЙ ДИЛЕР В ВОЛГОГРАДЕ</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MenuBarNew setShowModal={setShowModal} />
            <BarMenu />
            <BannerFavorite refs={{ refCards }} />
            <FavoriteCarsNew
                refCards={refCards}
                favArr={favArr}
                setFavArr={setFavArr}
                favArrUsed={favArrUsed}
                setFavArrUsed={setFavArrUsed}
                setShowModal={setShowModal}
            />
            {/* <FavoriteCars favArr={favArr} setFavArr={setFavArr} setShowModal={setShowModal} />
            <FavoriteCardsUsed favArrUsed={favArrUsed} setFavArrUsed={setFavArrUsed} setShowModal={setShowModal} /> */}
            <FooterMainNew setShowModal={setShowModal} refs={{ refFooter }} />

            {
                showModal && <Modal showModal={showModal} setShowModal={setShowModal} />
            }

            {
                showTradeInModal && <TradeinModal showTradeInModal={showTradeInModal} setShowTradeInModal={setShowTradeInModal} />
            }

        </>
    )
}

export default FavoriteCarPage





