
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { useRef, useState } from 'react'
import { AllCarDto} from '../../@types/dto'
import db, { Car } from '../../prisma'
import { NewCarComponent } from '../../src/component/actual/allNewCarPage/NewCarComponent'
import { FooterMain } from '../../src/component/actual/FooterMain'
import { MenuBar } from '../../src/component/Menu'
import { Modal } from '../../src/component/Modal'
import { TradeinModal } from '../../src/component/ModalTwo'


const AllNewCarPage: NextPage <{ cars: AllCarDto }> = ({ cars }) => {
  
  const [showModal, setShowModal] = useState(false)
  const [showTradeInModal, setShowTradeInModal] = useState(false)
  const refSales = useRef<HTMLDivElement>(null)
  const refTop = useRef<HTMLDivElement>(null)
  const refContact = useRef<HTMLDivElement>(null)
  const refAdvatages = useRef<HTMLDivElement>(null)
  const refFooter = useRef<HTMLDivElement>(null)
  const refForm = useRef<HTMLDivElement>(null)

  return (
    <>
      <Head>
        <title>АРКОНТ ОФИЦИАЛЬНЫЙ ДИЛЕР В ВОЛГОГРАДЕ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuBar refs={{ refSales, refContact, refAdvatages }} />
      <NewCarComponent  setShowModal={setShowModal} cars={cars}  />
      {/* <FooterMain  setShowTradeInModal={setShowTradeInModal} refs={{ refFooter  }} /> */}

      {
        showModal && <Modal showModal={showModal} setShowModal={setShowModal} />
      }

      {
        showTradeInModal && <TradeinModal showTradeInModal={showTradeInModal} setShowTradeInModal={setShowTradeInModal} />
      }

    </>
  )
}


export const getServerSideProps: GetServerSideProps = async (context) => {
  const cars = await db.car.findMany(
              {
                  where: {
                      active: true,
                  },
                  include: {
                      CarModel: true,
                      CarComplectation: true,
                      CarModification: true,
                      extras: true,
                      DealerModel: true,
                  }
              }
  )

  return {
    props: {
      cars: JSON.parse(JSON.stringify(cars)),
    }
  }
}

export default AllNewCarPage





