
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { useRef, useState } from 'react'
import { FooterMain } from '../../src/component/actual/FooterMain'
import { CarSale } from '../../src/component/actual/tradeinPage/CarSale'
import { MainBannerTradeIn } from '../../src/component/actual/tradeinPage/MainBannerTradeIn'
import { ModalPrice } from '../../src/component/actual/tradeinPage/ModalPrice'
import { TradeInForm } from '../../src/component/actual/tradeinPage/TradeInForm'
import { TradeinStepper } from '../../src/component/actual/tradeinPage/TradeinStepper'
import BarMenu from '../../src/component/BarMenu'
import { MenuBar } from '../../src/component/Menu'
import { Modal } from '../../src/component/Modal'
import { TradeinModal } from '../../src/component/ModalTwo'


const TradeInPage: NextPage = () => {

  const [showModal, setShowModal] = useState(false)
  const [showModalPrice, setShowModalPrice] = useState(false)
  const [showTradeInModal, setShowTradeInModal] = useState(false)
  const refSales = useRef<HTMLDivElement>(null)
  const refTop = useRef<HTMLDivElement>(null)
  const refContact = useRef<HTMLDivElement>(null)
  const refAdvatages = useRef<HTMLDivElement>(null)
  const refFooter = useRef<HTMLDivElement>(null)
  const refForm = useRef<HTMLDivElement>(null)
  const [carPrice, setCarPrice] = useState('')

  return (
    <>
      <Head>
        <title>АРКОНТ Трейд-ин</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuBar />
      <BarMenu />
      <MainBannerTradeIn setShowModal={setShowModal} refs={{ refForm }} />
      <CarSale  setCarPrice={setCarPrice} carPrice={carPrice}  setShowModalPrice={setShowModalPrice}/>
      <TradeinStepper refs={{ refForm }} />
      {/* <TradeInForm /> */}
      <FooterMain setShowTradeInModal={setShowTradeInModal} refs={{ refFooter }} />

      {
        showModal && <Modal showModal={showModal} setShowModal={setShowModal} />
      }

      {
        showTradeInModal && <TradeinModal showTradeInModal={showTradeInModal} setShowTradeInModal={setShowTradeInModal} />
      }

      {
        showModalPrice && <ModalPrice   carPrice={carPrice} showModalPrice={showModalPrice} setShowModalPrice={setShowModalPrice} />
      }

    </>
  )
}

export default TradeInPage





