
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { useRef, useState } from 'react'
import { FooterMain } from '../../src/component/actual/FooterMain'
import { CarSale } from '../../src/component/actual/tradeinPage/CarSale'
import { MainBannerTradeIn } from '../../src/component/actual/tradeinPage/MainBannerTradeIn'
import { TradeInForm } from '../../src/component/actual/tradeinPage/TradeInForm'
import { TradeinStepper } from '../../src/component/actual/tradeinPage/TradeinStepper'
import { MenuBar } from '../../src/component/Menu'
import { Modal } from '../../src/component/Modal'
import { TradeinModal } from '../../src/component/ModalTwo'


const TradeInPage: NextPage = () => {
  
  const [showModal, setShowModal] = useState(false)
  const [showTradeInModal, setShowTradeInModal] = useState(false)
  const refSales = useRef<HTMLDivElement>(null)
  const refTop = useRef<HTMLDivElement>(null)
  const refContact = useRef<HTMLDivElement>(null)
  const refAdvatages = useRef<HTMLDivElement>(null)
  const refFooter = useRef<HTMLDivElement>(null)
  const refForm = useRef<HTMLDivElement>(null)

  return (
    <>
      <Head>
        <title>АРКОНТ ОФИЦИАЛЬНЫЙ ДИЛЕР В ВОЛГОГРАДЕ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuBar  />
      <MainBannerTradeIn   refs={{ refForm  }} />
      <CarSale />
      <TradeinStepper   refs={{ refForm }} />
      {/* <TradeInForm /> */}
      <FooterMain  setShowTradeInModal={setShowTradeInModal} refs={{ refFooter  }} />

      {
        showModal && <Modal showModal={showModal} setShowModal={setShowModal} />
      }

      {
        showTradeInModal && <TradeinModal showTradeInModal={showTradeInModal} setShowTradeInModal={setShowTradeInModal} />
      }

    </>
  )
}

export default TradeInPage





