import type {NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useRef, useState } from 'react'
import { FooterMain } from '../../src/component/actual/FooterMain'
import WatchedCars from '../../src/component/actual/watchedCarPage/WatchedCards'
import BarMenu from '../../src/component/BarMenu'
import { MenuBar } from '../../src/component/Menu'
import { Modal } from '../../src/component/Modal'
import { TradeinModal } from '../../src/component/ModalTwo'

const WatchedCarPage: NextPage = () => {

    const [showModal, setShowModal] = useState(false)
    const [showTradeInModal, setShowTradeInModal] = useState(false)
    const [watchedArr, setWatchedArr] = useState([]);


    const refSales = useRef<HTMLDivElement>(null)
    const refTop = useRef<HTMLDivElement>(null)
    const refContact = useRef<HTMLDivElement>(null)
    const refAdvatages = useRef<HTMLDivElement>(null)
    const refFooter = useRef<HTMLDivElement>(null)
    const refForm = useRef<HTMLDivElement>(null)


    useEffect(() => {
        async function start() {
            const res = await fetch('/api/favorite/watchedcar/getAll', {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json'
                }
            })
            if (res.ok) {
                const result = await res.json()
                setWatchedArr(result.watchedCarUser.watchedCars)
            }
        }
        start()
    }, [])




    return (
        <>
            <Head>
                <title>АРКОНТ ОФИЦИАЛЬНЫЙ ДИЛЕР В ВОЛГОГРАДЕ</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MenuBar />
            <BarMenu />
            <WatchedCars watchedArr={watchedArr} setWatchedArr={setWatchedArr} setShowModal={setShowModal} />
            <FooterMain  setShowTradeInModal={setShowTradeInModal} refs={{ refFooter  }} />

            {
                showModal && <Modal showModal={showModal} setShowModal={setShowModal} />
            }

            {
                showTradeInModal && <TradeinModal showTradeInModal={showTradeInModal} setShowTradeInModal={setShowTradeInModal} />
            }

        </>
    )
}

export default WatchedCarPage





