import type {NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useRef, useState } from 'react'
import { FooterMain } from '../../src/component/actual/FooterMain'
import WatchedCars from '../../src/component/actual/watchedCarPage/WatchedCards'
import BarMenu from '../../src/component/BarMenu'
import { MenuBar } from '../../src/component/Menu'
import { Modal } from '../../src/component/Modal'
import { TradeinModal } from '../../src/component/ModalTwo'
import { MenuBarNew } from '../../src/component/actual/menuNew/Menu'
import { FooterMainNew } from '../../src/component/actual/menuNew/FooterMain'
import { BannerWatched } from '../../src/component/actual/watchedCarPage/BannerWatched'
import WatchedCarsNew from '../../src/component/actual/watchedCarPage/cards/WatchedCarsNew'

const WatchedCarPage: NextPage = () => {

    const [showModal, setShowModal] = useState(false)
    const [showTradeInModal, setShowTradeInModal] = useState(false)
    const [watchedArr, setWatchedArr] = useState([]);
    const [watchedArrUsed, setWatchedArrUsed] = useState([]);
    const refCards = useRef<HTMLDivElement>(null)
    const refFooter = useRef<HTMLDivElement>(null)

    useEffect(() => {
        async function start() {
            const res = await fetch('/api/favorite/watchedcar/getAll', {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json'
                }
            })
            if (res.ok) {
                const result = await res.json()
                setWatchedArr(result.watchedCarUser.watchedCars)
            }
        }
        start()

  
    }, [])

    useEffect(() => {
        async function start() {
            const res = await fetch('/api/usedwatched/getAll', {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json'
                }
            })
            if (res.ok) {
                const result = await res.json()
                setWatchedArrUsed(result.watchedCarUser.watchedUsedCars)
            }
            
        }
        start()
    }, [])





    return (
        <>
            <Head>
                <title>АРКОНТ ОФИЦИАЛЬНЫЙ ДИЛЕР В ВОЛГОГРАДЕ</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MenuBarNew setShowModal={setShowModal} />
            <BarMenu />
            <BannerWatched refs={{ refCards }} />
            <WatchedCarsNew
                refCards={refCards}
                watchedArr={watchedArr}
                setWatchedArr={setWatchedArr}
                watchedArrUsed={watchedArrUsed}
                setWatchedArrUsed={setWatchedArrUsed}
                setShowModal={setShowModal}
            />
            {/* <WatchedCars watchedArr={watchedArr} setWatchedArr={setWatchedArr} setShowModal={setShowModal} /> */}
            <FooterMainNew setShowModal={setShowModal} refs={{ refFooter }} />

            {
                showModal && <Modal showModal={showModal} setShowModal={setShowModal} />
            }

            {
                showTradeInModal && <TradeinModal showTradeInModal={showTradeInModal} setShowTradeInModal={setShowTradeInModal} />
            }

        </>
    )
}

export default WatchedCarPage





