// @ts-check
const { PrismaClient } = require('@prisma/client');
const db = new PrismaClient()

const dealerList = [
    {
        // id: 0,
        name: 'Renault Арконт Волгоград',
        label: `/uploads/offices/renault.jpeg`,
        photo: `/uploads/offices/renault.jpeg`,
        city: 'Волгоград',
        address: 'ул. Вильнюсская, 42/2',
        phone: '+7 (8442) 74-65-81',
        brend: 'Renault'
    },
    // {
    //     id: 1,
    //     name: 'KIA Арконт',
    //     label: `${kia.src}`,
    //     photo: `${kiaOffice.src}`,
    //     city: 'Волгоград',
    //     address: 'ул. Вильнюсская, 42/2',
    //     phone: '+7 (8442) 74-65-82',
    //     brend: 'KIA',
    // },
    // {
    //     id: 2,
    //     name: 'Volkswagen Арконт на Монолите',
    //     label: `${volkswagen.src}`,
    //     photo: `${volkswagenOffice.src}`,
    //     city: 'Волгоград',
    //     address: 'пр-т Ленина, 113Д',
    //     phone: '+7 (8442) 74-65-75',
    //     brend: 'Volkswagen',
    // },
    // {
    //     id: 3,
    //     name: 'Nissan Арконт на Еременко 7Б',
    //     label: `${nissan.src}`,
    //     photo: `${nissanOffice.src}`,
    //     city: 'Волгоград',
    //     address: 'ул. Ерёменко, 7Б',
    //     phone: '+7 (8442) 74-65-72',
    //     brend: 'Nissan',
    // },
    // {
    //     id: 4,
    //     name: 'Mitsubishi Арконт на Землячке',
    //     label: `${mithsubishi.src}`,
    //     photo: `${mitsubishiOffice.src}`,
    //     city: 'Волгоград',
    //     address: 'ул. Землячки, 19Г',
    //     phone: '+7 (8442) 74-65-42',
    //     brend: 'Mitsubishi',
    // },
    // {
    //     id: 5,
    //     name: 'Hyundai Арконт',
    //     label: `${hyundai.src}`,
    //     photo: `${hyundaiOffice.src}`,
    //     city: 'Волжский',
    //     address: 'пр-т Ленина, 359',
    //     phone: '+7 (8443) 44-51-07',
    //     brend: 'Hyundai',
    // },
    // {
    //     id: 6,
    //     name: 'Арконт с пробегом на Землячке',
    //     label: `${usedCars.src}`,
    //     photo: `${usedZemlOffice.src}`,
    //     city: 'Волгоград',
    //     address: 'ул. Землячки, 25',
    //     phone: '+7 (8442) 74-65-83',
    //     brend: 'C пробегом',
    // },
    // {
    //     id: 7,
    //     name: 'Арконт с пробегом в Волжском',
    //     label: `${usedCars.src}`,
    //     photo: `${usedVlzOffice.src}`,
    //     city: 'Волжский',
    //     address: 'пр-т Ленина, 359',
    //     phone: '+7 (8443) 44-51-08',
    //     brend: 'C пробегом',

    // },
    // {
    //     id: 8,
    //     name: 'УАЗ Арконт',
    //     label: `${uaz.src}`,
    //     photo: `${usedVlzOffice.src}`,
    //     city: 'Волгоград',
    //     address: 'ул. Вильнюсская, 42/1',
    //     phone: '+7 (8442) 52-50-64',
    //     brend: 'УАЗ',
    // },
    // {
    //     id: 9,
    //     name: 'Chery Арконт',
    //     label: `${chery.src}`,
    //     photo: `${cheryOffice.src}`,
    //     city: 'Волгоград',
    //     address: 'ул. Землячки 19Г',
    //     phone: '+7 (8442) 20-21-73',
    //     brend: 'Chery',
    // },
    // {
    //     id: 10,
    //     name: 'EXEED Арконт',
    //     label: `${exeed.src}`,
    //     photo: `${exeedOffice.src}`,
    //     city: 'Волгоград',
    //     address: 'г. Волгоград, ул. Землячки, 25',
    //     phone: '+7 (8442) 20-21-73',
    //     brend: 'EXEED',
    // },
    // {
    //     id: 11,
    //     name: 'Официальный сервис Datsun «Арконт»',
    //     label: `${datsun.src}`,
    //     photo: `${withoutPhotoOffice.src}`,
    //     city: 'Волгоград',
    //     address: 'ул. Ерёменко, 7Б',
    //     phone: '+7 (8442) 59-97-83',
    //     brend: 'Datsun',
    // },
    // {
    //     id: 12,
    //     name: 'Официальный сервис Datsun «Арконт» (Волжский)',
    //     label: `${datsun.src}`,
    //     photo: `${withoutPhotoOffice.src}`,
    //     city: 'Волжский',
    //     address: 'пр-т. им. Ленина, 359',
    //     phone: '+7 (8443) 20-50-15',
    //     brend: 'Datsun',
    // },
    // {
    //     id: 13,
    //     name: 'Официальный сервис Datsun «Арконт»',
    //     label: `${datsun.src}`,
    //     photo: `${withoutPhotoOffice.src}`,
    //     city: 'Волгоград',
    //     address: 'ул. Неждановой, 12',
    //     phone: '+7 (8442) 59-64-45',
    //     brend: 'Datsun',
    // },
    // {
    //     id: 14,
    //     name: 'Официальный сервис Opel «Арконт»',
    //     label: `${opel.src}`,
    //     photo: `${withoutPhotoOffice.src}`,
    //     city: 'Волгоград',
    //     address: 'ул. Вильнюсская, 42/1',
    //     phone: '+7 (8442) 52-50-45',
    //     brend: 'Opel',
    // },
    // {
    //     id: 15,
    //     name: 'Официальный сервис Ford «Арконт»',
    //     label: `${ford.src}`,
    //     photo: `${withoutPhotoOffice.src}`,
    //     city: 'Волгоград',
    //     address: 'ул. Вильнюсская, 42/1',
    //     phone: '+7 (8442) 59-70-50',
    //     brend: 'Ford',
    // },
    // {
    //     id: 16,
    //     name: 'FAW Арконт',
    //     label: `${faw.src}`,
    //     photo: `${withoutPhotoOffice.src}`,
    //     city: 'Волгоград',
    //     address: 'ул. Вильнюсская, 42',
    //     phone: '+7 (8442) 22-05-77',
    //     brend: 'Faw',
    // },
    // {
    //     id: 17,
    //     name: 'Geely Арконт',
    //     label: `${geely.src}`,
    //     photo: `${withoutPhotoOffice.src}`,
    //     city: 'Волгоград',
    //     address: 'ул.Нежданова, 12',
    //     phone: '+7 (8442) 20-49-73',
    //     brend: 'Geely',
    // },
    // {
    //     id: 18,
    //     name: 'HISUN Арконт',
    //     label: `${hisun.src}`,
    //     photo: `${withoutPhotoOffice.src}`,
    //     city: 'Волгоград',
    //     address: 'пр-т им. В.И. Ленина, 113Д',
    //     phone: '+7 (8442) 20-49-74',
    //     brend: 'HISUN',
    // },
    // {
    //     id: 19,
    //     name: 'LOVOL Арконт',
    //     label: `${lovol.src}`,
    //     photo: `${withoutPhotoOffice.src}`,
    //     city: 'Волгоград',
    //     address: 'ул. Историческая, д.170',
    //     phone: '+7 (8442) 20-49-74',
    //     brend: 'LOVOL',
    // },
]

async function startSeed() {
    const res = await db.offices.createMany({
        data: dealerList
    })
}

startSeed()