//@ts-ignore
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { MenuBar } from '../src/component/Menu'
import { Modal } from '../src/component/Modal'
import { TradeinModal } from '../src/component/ModalTwo'
import { useEffect, useRef, useState } from 'react'
import BarMenu from '../src/component/BarMenu'
import db from '../prisma'
// import { useUtm } from '../src/hooks/useUtm'
import { MainCard } from '../src/component/MainCard'
import { Labels } from '../src/component/actual/Labels'
import { QuestionForm } from '../src/component/actual/QuestionForm'
import { FooterMain } from '../src/component/actual/FooterMain'
import { AllCarDto, AllUsedCarDto, CarDtoWithoutFavorite } from '../@types/dto'
import { CarouselComponent } from '../src/component/actual/Carousel'
import { CarouselComponentUsed } from '../src/component/actual/CarouselUsed'
import { SwiperEl } from '../src/component/actual/slider/Swiper'
import { SwiperElUsed } from '../src/component/actual/sliderUsed/SwiperUsed'
import { getDataFromRedis, getRedisInstance } from '../src/services/redis'
import { MenuBarNew } from '../src/component/actual/menuNew/Menu'
import { FooterMainNew } from '../src/component/actual/menuNew/FooterMain'
import BrandsCards from '../src/component/actual/brendsPages/all/BrandsCards'
import { Box } from '@mui/material'
import BrandsMap from '../src/component/actual/brendsPages/all/BrandsMap'


const Home: NextPage<{ cars: AllCarDto, carsUsed: AllUsedCarDto }> = ({ cars, carsUsed }) => {

  const [showModal, setShowModal] = useState(false)
  const [showTradeInModal, setShowTradeInModal] = useState(false)
  const refFooter = useRef<HTMLDivElement>(null)
  const [mobileAdaptive, setMobileAdaptive] = useState(false);

  // const refSales = useRef<HTMLDivElement>(null)
  // const refTop = useRef<HTMLDivElement>(null)
  // const refContact = useRef<HTMLDivElement>(null)
  // const refAdvatages = useRef<HTMLDivElement>(null)

  // const [modelName, setModelName] = useState<string>(null)
  // useEffect(() => {
  //   const utm = new URLSearchParams(location.search).get('utm_mdl')
  //   if(utm === 'rio_2022') {
  //     setModelName('Rio')
  //   }
  // }, [])
  // const { utm_mdl } = useUtm(['utm_mdl'])

  // Определение количества отображаемых элементов в зависимости от ширины экрана
  useEffect(() => {
    function handleResize() {
      if (window.innerWidth < 768) {
        setMobileAdaptive(true);
      } else {
        setMobileAdaptive(false);
      }
    }
    window.addEventListener("resize", handleResize);
    handleResize();
    return () => window.removeEventListener("resize", handleResize);
  }, [])

  return (
    <>
      <Head>
        <title>АРКОНТ ОФИЦИАЛЬНЫЙ ДИЛЕР В ВОЛГОГРАДЕ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuBarNew setShowModal={setShowModal} />
      <BarMenu />

      <div className='background'>
        <div className='content'>

          <MainCard />
          {/* <BrandsCards /> */}
          <Labels />

          {mobileAdaptive == false ?
            <>
              <SwiperEl cars={cars} />
              <SwiperElUsed carsUsed={carsUsed} />
            </>
            :
            <>
              <CarouselComponent cars={cars} />
              <CarouselComponentUsed carsUsed={carsUsed} />
            </>

          }
        </div>
      </div >
      <div className='background'>
        <div className='content'>
          <QuestionForm />
          <div className='title'>Сервисные центры Арконт</div>
          <BrandsMap />
        </div>
      </div >

      <FooterMainNew setShowModal={setShowModal} refs={{ refFooter }} />
      {
        showModal && <Modal showModal={showModal} setShowModal={setShowModal} />
      }

      {
        showTradeInModal && <TradeinModal showTradeInModal={showTradeInModal} setShowTradeInModal={setShowTradeInModal} />
      }



      <style jsx>
        {` 
          .background {
            display: flex; 
            justify-content: center;
            width: '100%' ;
          }
  
          .content {
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 1179px; 
          }

          .title {
            display: flex;
            justify-content: start;
            width: 100%;
            font-family: 'Roboto',sans-serif;
            margin-top: 20px;
            font-size: 25px;
            font-weight: bold;
          }

          @media(max-width: 1300px) {
            .content {  
              width: 970px; 
            }
          }

          @media(max-width: 900px) {
            .content{  
              width: 640px; 
            }
          }

          @media(max-width: 640px) {
            .content{  
              width: 450px; 
            }
            .title {
              justify-content: center;
            }
          }    
          
          @media(max-width: 450px) {
            .content{  
              width: 360px; 
            }
          }

          @media(max-width: 360px) {
            .background {
              padding-left: 10px;
              padding-right: 10px;
            }
            .content{  
              width:90%; 
            }
          }

        `}
      </style>
    </>
  )

}



export const getServerSideProps: GetServerSideProps = async (context) => {
  let cars: CarDtoWithoutFavorite[] = []; // Объявление переменной cars
  let carsUsed: AllUsedCarDto = []; // Объявление переменной carsUsed
  try {
    // Получаем данные из Redis и парсим их в массив объектов
    const carsData: string = await getDataFromRedis('cars');
    const carsUsedData: string = await getDataFromRedis('carsUsed');

    if (!carsData) {
      cars = await db.car.findMany(
        {
          where: {
            active: true,
          },
          include: {
            CarModel: true,
            CarComplectation: true,
            CarModification: true,
            extras: true,
            DealerModel: true,
          },
        }
      );
      // Сохраняем данные в Redis на день и преобразовываем дату 
      // getRedisInstance().set('cars', JSON.stringify(cars), 'EX', 86400);
      getRedisInstance().set('cars', JSON.stringify(cars, (key, value) => {
        if (key === 'createdAt') {
          return new Date(value).toISOString(); // преобразование даты в строку
        }
        return value;
      }), 'EX', 86400);
    } else {
      cars = JSON.parse(carsData) as CarDtoWithoutFavorite[]; // Преобразование строки в массив объектов типа Car
    }

    if (!carsUsedData) {
      carsUsed = await db.usedCars.findMany({
        where: {
          active: true,
        }
      });

      // Сохраняем данные в Redis и преобразовываем дату 
      // getRedisInstance().set('carsUsed', JSON.stringify(carsUsed), 'EX', 86400);
      getRedisInstance().set('carsUsed', JSON.stringify(carsUsed, (key, value) => {
        if (key === 'createdAt') {
          return new Date(value).toISOString(); // преобразование даты в строку
        }
        return value;
      }), 'EX', 86400);
      (err, reply) => {
        if (err) {
          console.log('Ошибка при записи данных в Redis:', err);
          return;
        }
        console.log('Данные успешно записаны в Redis:', reply);
      }
    } else {
      carsUsed = JSON.parse(carsUsedData) as AllUsedCarDto; // Преобразование строки в массив объектов типа UsedCar
    }
    // Устанавливаем заголовки Cache-Control и ETag
    context.res.setHeader('Cache-Control', 'public, max-age=86400'); // Максимальное время кэширования - 4 часа
    context.res.setHeader('ETag', 'some-unique-value'); // Уникальное значение ETag
    // Защита от атак XSS
    context.res.setHeader('X-XSS-Protection', '1; mode=block');
    // Защита от клик-джекинга
    context.res.setHeader('X-Frame-Options', 'SAMEORIGIN');
    // Защита от MIME-типа сниффинга
    context.res.setHeader('X-Content-Type-Options', 'nosniff');
    return {
      props: {
        cars,
        carsUsed,
      },
    };
  } catch (error) {
    console.error('Error querying the database:', error);
    return {
      props: {
        cars: [],
        carsUsed: [],
      },
    };
  }
};

export default Home